// Code generated by Thrift Compiler (0.14.1). DO NOT EDIT.

package agent

import(
	"bytes"
	"context"
	"fmt"
	"time"
	"github.com/apache/thrift/lib/go/thrift"
	"github.com/erda-project/oap-plugins-gen-go/jaeger-thrift/jaeger"
	"github.com/erda-project/oap-plugins-gen-go/jaeger-thrift/zipkincore"

)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = time.Now
var _ = bytes.Equal

var _ = jaeger.GoUnusedProtection__
var _ = zipkincore.GoUnusedProtection__

func init() {
}

